# Dockerfile_back_end

# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory
WORKDIR /app
COPY back_end/package*.json ./

RUN npm install

VOLUME /app

# Expose the backend port
EXPOSE 5000

# Set the environment variables for MongoDB connection
ENV MONGO_URL=mongodb://mongo:27017/mydatabase

RUN npm install -g nodemon

# Run the backend service
CMD ["nodemon", "server.js"]
