services:
  front_end: 
    container_name: dp_front
    build:
      context: .
      dockerfile: Dockerfile_front_end
    volumes:
      - /home/fazeel/dev_portfolio/front_end:/app
    ports:
      - 3000:3000
  back_end:
    container_name: dp_back
    build:
      context: .
      dockerfile: Dockerfile_back_end
    volumes:
      - /home/fazeel/dev_portfolio/back_end:/app
    ports:
      - 5000:5000
  mongo:
    container_name: dp_mongo
    build:
      context: .
      dockerfile: Dockerfile_mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file: .env
  
  mongo_express:
    container_name: dp_mexpress
    build:
      context: .
      dockerfile: Dockerfile_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    env_file: .env
    
volumes:
  mongo-data:
    external: true
