services:
  front_end: 
    container_name: dp_front
    build:
      context: .
      dockerfile: Dockerfile_front_end
    ports:
      - 3000:3000
  back_end:
    container_name: dp_back
    build:
      context: .
      dockerfile: Dockerfile_back_end
    ports:
      - 5000:5000
  mongo:
    container_name: dp_mongo
    build:
      context: .
      dockerfile: Dockerfile_mongo
    volumes:
      - mongo-data:/data/db
      - /home/fazeel/dev_portfolio/mongod.conf:/etc/mongod.conf
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  mongo-data:
    external: true
