services:
  front_end: 
    container_name: dp_front
    build:
      context: .
      dockerfile: Dockerfile_front_end
    volumes:
      - /home/fazeel/dev_portfolio/front_end:/app
    ports:
      - 3000:3000
  back_end:
    container_name: dp_back
    build:
      context: .
      dockerfile: Dockerfile_back_end
    volumes:
      - /home/fazeel/dev_portfolio/back_end:/app
    ports:
      - 5000:5000
  mongo:
    container_name: dp_mongo
    build:
      context: .
      dockerfile: Dockerfile_mongo
    volumes:
      - mongo-data:/data/db
      - /home/fazeel/dev_portfolio/mongod.conf:/etc/mongod.conf
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo_express:
    container_name: dp_mexpress
    build:
      context: .
      dockerfile: Dockerfile_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: fazeel
      ME_CONFIG_BASICAUTH_PASSWORD: fazeel
volumes:
  mongo-data:
    external: true
